spring:
  application:
    name: energy-percentage-service

  datasource:
    url: jdbc:postgresql://localhost:5432/energy_usage_db
    username: disysuser
    password: disyspw
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

usage:
  datasource:
    url: jdbc:postgresql://localhost:5432/energy_usage_db
    username: disysuser
    password: disyspw
    driver-class-name: org.postgresql.Driver

server:
  port: 8083
