version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=disysuser
      - POSTGRES_PASSWORD=disyspw
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U disysuser"]
      interval: 10s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres_data:
